services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-php
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - php

  db:
    image: postgres:latest
    container_name: laravel-db
    environment:
      POSTGRES_DB: decameron_nz8u
      POSTGRES_USER: decameron_nz8u_user
      POSTGRES_PASSWORD: syRcZwelzA6wULBBzNsAoYPyvkuIRv1j
    volumes:
      - laravel_db_data:/var/lib/postgresql/data
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  laravel_db_data:
