services:
  # Servicio para PHP-FPM
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-php
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db

  # Servicio para Nginx
  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - laravel-network
    depends_on:
      - php

  # Servicio para base de datos (por ejemplo, PostgreSQL)
  db:
    image: postgres:latest
    container_name: laravel-db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - laravel_db_data:/var/lib/postgresql/data
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  laravel_db_data:
    driver: local
