services:
  - type: web
    name: laravel-api
    env: docker
    repo: https://github.com/JGCODE47/decameron
    dockerfilePath: docker/php/Dockerfile
    dockerContext: .
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
    startCommand: php-fpm
